title: Mi primer Jupyter Book
author: Juan Luis Aguayo
language: es

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence
    - deflist

latex:
  latex_engine: xelatex
  use_jupyterbook_latex: true

sphinx:
  extra_extensions:
    - sphinx_proof

  config:

    numfig: true
    math_numfig: true
    numfig_secnum_depth: 2

    latex_elements:
      papersize: letterpaper
      pointsize: 11pt

      preamble: |
        % ===== MATEMATICA =====
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{amsfonts}
        \usepackage{mathtools}
        \usepackage{bm}
        \usepackage{siunitx}

        % ===== PROBABILIDAD =====
        \newcommand{\E}{\mathbb{E}}
        \newcommand{\Prob}{\mathbb{P}}
        \newcommand{\Var}{\mathrm{Var}}
        \newcommand{\Cov}{\mathrm{Cov}}
        \newcommand{\Entropy}{\mathrm{H}}
        \newcommand{\MI}{\mathrm{I}}
        \newcommand{\KL}{\mathrm{D}_{KL}}

        % ===== NUMERACION =====
        \numberwithin{equation}{chapter}

        % ===== TIPOGRAFIA =====
        \usepackage{microtype}
